# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Open Diplomatic Editions
tagline:          'A peer-reviewed publication for diplomatic editions'
description:      'ODE: a peer-reviewed publication for diplomatic editions, available under CC licenses'
#baseurl: 'http://diplomaticeditions.github.io/'
baseurl: ''
#baseurl: '/ode-draft/'



author:
  name:           'Neel Smith'
 
paginate:         5

links:
  - title: Why open diplomatic editions?
    url: /why	
  - title: About ODE
    url: /about	
  - title: Guidelines for submission
    url: /guidelines	
  - title: ODE editorial board
    url: /edboard
  - title: Github source for this web site
    url: https://github.com/diplomaticeditions/diplomaticeditions.github.io
    external: true

   